export const BUSINESS_COURSES = [
  {
    id: 'business-1',
    track: 'Business',
    title: 'Unit economics: the numbers that determine whether your business survives',
    subtitle: 'CAC, LTV, payback period, gross margin & the framework for knowing if your model actually works',
    duration: '14 m',
    level: 'PhD',
    xp: 180,
    sections: [
      {
        title: 'The four numbers you must know',
        content: 'CAC (Customer Acquisition Cost): the total cost to acquire one customer. LTV (Lifetime Value): the total gross profit a customer generates over their relationship with you. Payback period: how long it takes to recover CAC from the gross margin generated by a customer. Gross margin: revenue minus cost of goods sold, expressed as a percentage. These four numbers tell you whether your business model is viable, how fast you can grow, and whether you\'re burning cash to acquire customers who will never be profitable.',
        keyPoints: [
          'CAC, LTV, payback period, gross margin — the foundational four',
          'LTV:CAC ratio should be at least 3:1 for a healthy model',
          'Payback period under 12 months is generally considered healthy for SaaS',
        ],
      },
      {
        title: 'The LTV:CAC trap',
        content: 'LTV:CAC of 3:1 is the widely cited benchmark. But LTV is a projection, not a fact. Companies routinely overestimate LTV by using optimistic churn assumptions, ignoring support costs, or calculating on revenue rather than gross profit. The honest calculation: LTV = (average revenue per customer per month × gross margin %) ÷ monthly churn rate. If your gross margin is 60%, your average MRR per customer is $50, and monthly churn is 3%, your LTV is ($50 × 0.60) ÷ 0.03 = $1,000. Not $50 ÷ 0.03 = $1,667.',
        keyPoints: [
          'LTV must be calculated on gross profit, not revenue',
          'Include support and success costs in your gross margin calculation',
          'Churn is the denominator — small errors in churn estimates have large LTV impacts',
        ],
      },
      {
        title: 'Gross margin: the constraint on everything',
        content: 'Gross margin determines how much of each revenue dollar is available to fund growth, operations, and profit. A business with 20% gross margin has $0.20 of every revenue dollar to spend on sales, marketing, G&A, and R&D. A business with 80% gross margin has $0.80. The difference in investable resources — at the same revenue — is 4×. This is why software businesses (typically 70–90% gross margin) can grow faster and reach profitability more easily than services businesses (typically 20–40% gross margin).',
        keyPoints: [
          'Gross margin = (revenue − COGS) ÷ revenue',
          'High gross margin funds growth; low gross margin constrains it',
          'Business model determines gross margin ceiling — know yours',
        ],
      },
    ],
  },
  {
    id: 'business-2',
    track: 'Business',
    title: 'Fundraising fundamentals: what investors actually want',
    subtitle: 'How VCs think, what they\'re looking for, how to position your pitch & the terms that matter',
    duration: '15 m',
    level: 'PhD',
    xp: 190,
    sections: [
      {
        title: 'How VCs think about returns',
        content: 'Venture capital is a power law business. A VC fund needs one investment to return the entire fund (a "fund returner") to make the economics work. This means VCs are not looking for businesses that will reliably return 3–5×; they\'re looking for businesses that might return 50–100×. This changes everything about what they\'re evaluating: they\'re not asking "is this business viable?" — they\'re asking "could this be a billion-dollar company?" A good business with a capped market is a bad VC investment.',
        keyPoints: [
          'VC returns follow a power law — one investment must return the fund',
          'VCs seek 50–100× potential, not reliable 3–5× returns',
          'Market size is a filter before product quality',
        ],
      },
      {
        title: 'What investors are actually evaluating',
        content: 'The Sequoia framework: Why now? Why you? Why this market? Why this model? "Why now" is critical — if this idea was possible five years ago, why hasn\'t it been built? What has changed? Regulatory, technological, behavioural? Investors also evaluate team (track record, domain expertise, coachability), market (size, growth, defensibility), traction (revenue, growth rate, retention), and product (is it genuinely better, or just different?). Of these, team and market are weighted most heavily at early stages.',
        keyPoints: [
          'Why now, why you, why this market — the three fundamental questions',
          'Team and market weighted highest at seed and Series A',
          'Traction is the best counter-argument to every other concern',
        ],
      },
      {
        title: 'Terms that matter and terms that don\'t',
        content: 'Valuation gets the most attention and matters the least (in the long run). The terms that matter: liquidation preference (1× non-participating is standard; 2× participating is founder-unfriendly), pro-rata rights (the right to invest in future rounds — affects dilution), board composition (who controls the company), and anti-dilution provisions (weighted average is standard; full ratchet is onerous). The biggest mistake founders make is optimising for valuation while ignoring terms that affect control and economics at exit.',
        keyPoints: [
          'Valuation matters less than terms at exit',
          '1× non-participating liquidation preference is the founder-friendly standard',
          'Board composition determines who controls strategic decisions',
        ],
      },
    ],
  },
  {
    id: 'business-3',
    track: 'Business',
    title: 'Operations: building a business that works without you',
    subtitle: 'SOPs, delegation, hiring for function, and the systems that make a business scalable',
    duration: '13 m',
    level: 'Masters',
    xp: 155,
    sections: [
      {
        title: 'Why founders can\'t scale themselves',
        content: 'In the early days, the founder is the business. They make every decision, do every task, hold all the context. This is appropriate at zero revenue. It is catastrophic at $1M+ in revenue. The transition from "founder does everything" to "founder builds systems and people" is the most important and most difficult transition in a company\'s life. Most founders fail to make it — not because they lack skill, but because they lack the will to let go and the discipline to build systems before they urgently need them.',
        keyPoints: [
          'Founder-as-operator is appropriate early and catastrophic at scale',
          'The transition is systems-building, not just hiring',
          'Build systems before you urgently need them — not after',
        ],
      },
      {
        title: 'Standard Operating Procedures that actually get used',
        content: 'An SOP that\'s not followed is not an SOP — it\'s a document. SOPs get ignored when they\'re too long, too vague, not updated when processes change, or not embedded in the workflow where the work happens. Effective SOPs are: short (one page or less for simple processes), specific (exact steps, not principles), stored where the work happens (in your PM tool, not in a Google Drive folder no one opens), and owned by the person who does the work (not written by management for workers).',
        keyPoints: [
          'SOPs must be short, specific, and stored where the work happens',
          'Owned by the executor, not the manager',
          'Review SOPs when processes change — stale SOPs are worse than none',
        ],
      },
      {
        title: 'Hiring for function, not for title',
        content: 'The most common hiring mistake: hiring a VP of Marketing when you need someone to run paid acquisition. The title and the function are not the same. A VP of Marketing is a strategist and leader; the function you need is a hands-on media buyer. Hiring a senior leader for a hands-on role is expensive, demotivating for the hire, and produces worse results than hiring a specialist. Define the function first — the specific outputs you need from this role — then find the level of person who can deliver those outputs.',
        keyPoints: [
          'Define the function (specific outputs) before writing the job description',
          'Senior leaders are demotivated by execution-heavy roles',
          'Match level to actual work, not to your aspiration for the company',
        ],
      },
    ],
  },
  {
    id: 'business-4',
    track: 'Business',
    title: 'Negotiation: the discipline behind every deal',
    subtitle: 'BATNA, anchoring, concession strategy & the frameworks that produce better outcomes in any negotiation',
    duration: '12 m',
    level: 'Masters',
    xp: 150,
    sections: [
      {
        title: 'The BATNA principle',
        content: 'BATNA stands for Best Alternative To a Negotiated Agreement — what you will do if this negotiation fails. Your BATNA determines your leverage. If you have a strong BATNA (another offer, another supplier, the ability to walk away), you negotiate from strength. If you have no BATNA (you need this deal to survive), you negotiate from weakness. The most important preparation before any negotiation is strengthening your BATNA — developing alternatives so you\'re never forced into an agreement you shouldn\'t accept.',
        keyPoints: [
          'BATNA = your power in a negotiation',
          'Strong BATNA = can walk away; weak BATNA = must accept',
          'Prepare your BATNA before entering any negotiation',
        ],
      },
      {
        title: 'Anchoring and first offers',
        content: 'The anchor is the first number stated in a negotiation. It has disproportionate influence on the final outcome — even when both parties know it\'s arbitrary. Research shows that who anchors first and how aggressively they anchor predicts the final settlement. The correct strategy: anchor first when you have information; anchor aggressively (more extreme than your target) to create room for concessions; anchor with a precise number (£127,500, not £130,000) — precision implies research and resists counter-offers.',
        keyPoints: [
          'Anchor first when you have information advantage',
          'Anchor aggressively — it shifts the zone of possible agreement',
          'Precise anchors ($127,500 vs $130,000) are more psychologically powerful',
        ],
      },
      {
        title: 'Concession strategy',
        content: 'Concessions tell a story. If you concede large amounts quickly, you signal that you had more room — which invites more demands. The professional concession pattern: make the first concession modest, subsequent concessions smaller than the previous one, and make each concession feel earned (require something in return, even if small). The final concession before your limit should be tiny — it signals you\'re near your floor. Never make a concession without getting something in return, even if that something is a commitment to move forward.',
        keyPoints: [
          'Concede in decreasing increments — signals you\'re approaching your limit',
          'Always require something in return for every concession',
          'Large, fast concessions signal you had more room',
        ],
      },
    ],
  },
  {
    id: 'business-5',
    track: 'Business',
    title: 'Strategy: making choices that compound',
    subtitle: 'Porter\'s Five Forces, competitive advantage, and the discipline of saying no',
    duration: '14 m',
    level: 'PhD',
    xp: 175,
    sections: [
      {
        title: 'What strategy actually means',
        content: 'Strategy is not a plan. A plan describes what you will do. Strategy describes why you will win — the specific combination of choices that creates a sustainable advantage over alternatives. Michael Porter\'s definition: strategy is the deliberate choice to perform different activities than rivals, or to perform similar activities differently, in a way that creates a unique value position. Most "strategies" are actually goals ("we will grow 30% this year") or plans ("we will launch in three new markets"). Neither is strategy.',
        keyPoints: [
          'Strategy = why you will win, not what you will do',
          'Real strategy requires explicit trade-offs (what you will NOT do)',
          'A goal is not a strategy; a plan is not a strategy',
        ],
      },
      {
        title: 'Competitive advantage: the three types',
        content: 'Porter identified three sources of sustainable competitive advantage: cost leadership (you produce at lower cost than competitors, enabling lower prices or higher margins), differentiation (you offer something competitors can\'t match that customers value enough to pay a premium for), and focus (you serve a specific segment better than generalists can). The mistake is trying to pursue multiple positions simultaneously — this leads to being "stuck in the middle," with no clear advantage. Pick one and commit.',
        keyPoints: [
          'Cost leadership, differentiation, or focus — pick one',
          'Stuck in the middle = no sustainable advantage',
          'Genuine differentiation must be valuable and hard to replicate',
        ],
      },
      {
        title: 'The discipline of saying no',
        content: 'Strategy requires sacrifice. Pursuing one position means declining opportunities in others. The hardest strategic decisions are not about what to do — they\'re about what not to do. Steve Jobs returned to Apple and cut 70% of its product line to focus. Warren Buffett has described his investment approach as having a very short list of things he\'ll consider and a very long list of things he won\'t. The clarity that comes from committed strategic choices — knowing exactly what you\'re for and what you\'re not — is both liberating and compounding.',
        keyPoints: [
          'Strategy requires explicit "no" decisions, not just "yes" decisions',
          'Cutting options focuses resources and sharpens identity',
          'What you decline defines your strategy as much as what you pursue',
        ],
      },
    ],
  },
] as const
