import type { Course } from '../courses'

export const termsCourses: Course[] = [
  {
    id: 'terms-mkt-b01',
    track: 'terms',
    title: 'Marketing Alphabet \u2014 Core Abbreviations',
    subtitle: 'KPI \u00b7 ROI \u00b7 CTR \u00b7 CAC \u00b7 LTV \u00b7 ROAS \u2014 every acronym your career runs on',
    level: 'Basic',
    xp: 80,
    duration: 18,
    module: 1,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Know every standard marketing abbreviation cold so you can read a campaign report, brief a media buyer, or sit in a strategy meeting without reaching for a glossary.',
    keyTerms: [
      { term: 'KPI', definition: 'Key Performance Indicator. A measurable value showing how effectively an objective is being met. A KPI without a target is just data.' },
      { term: 'ROI', definition: 'Return on Investment. Net profit divided by cost. Only meaningful when timeframe and attribution model are defined.' },
      { term: 'CTR', definition: 'Click-Through Rate. Clicks divided by impressions. CTR in isolation tells half the story.' },
      { term: 'CPM', definition: 'Cost Per Mille \u2014 cost per 1,000 impressions. The buying unit for awareness campaigns on Meta, YouTube, and programmatic platforms.' },
      { term: 'CPC', definition: 'Cost Per Click. Total ad spend divided by total clicks.' },
      { term: 'CAC', definition: 'Customer Acquisition Cost. Total sales and marketing spend divided by new customers acquired. The most important unit economics metric.' },
      { term: 'LTV', definition: 'Lifetime Value. Total revenue expected from a single customer. LTV must exceed CAC for the business model to be viable.' },
      { term: 'ROAS', definition: 'Return on Ad Spend. Revenue divided by ad spend. Does not account for margins.' },
      { term: 'CPA', definition: 'Cost Per Acquisition. The cost to acquire a specific desired action. The preferred direct-response optimization metric.' },
      { term: 'MQL', definition: 'Marketing Qualified Lead. A prospect who engaged with marketing content but has not yet been passed to sales.' },
      { term: 'SQL', definition: 'Sales Qualified Lead. A prospect the sales team has vetted and determined is ready for direct engagement.' },
      { term: 'NPS', definition: 'Net Promoter Score. Scores 9-10 are Promoters, 7-8 Passives, 0-6 Detractors. NPS equals percent Promoters minus percent Detractors.' },
      { term: 'AOV', definition: 'Average Order Value. Total revenue divided by number of orders. Raised through upsells, bundles, and minimum order thresholds.' },
      { term: 'CPL', definition: 'Cost Per Lead. Total ad spend divided by leads generated.' },
      { term: 'CR', definition: 'Conversion Rate. The percentage of visitors completing a desired action.' },
    ],
    quiz: [
      { q: 'A campaign generates $15,000 revenue from $5,000 spend. What is the ROAS?', options: ['2x', '3x', '5x', '0.33x'], correct: 1, explanation: 'ROAS = revenue / spend = $15,000 / $5,000 = 3x.' },
      { q: 'You spent $20,000 on marketing and acquired 200 customers. What is CAC?', options: ['$40', '$100', '$200', '$2,000'], correct: 1, explanation: 'CAC = $20,000 / 200 = $100.' },
      { q: 'Which metric measures cost to show your ad 1,000 times?', options: ['CPC', 'CPM', 'CPA', 'CPL'], correct: 1, explanation: 'CPM = Cost Per Mille \u2014 cost per thousand impressions.' },
      { q: 'What must LTV exceed for a business to be sustainable?', options: ['CPM', 'ROAS', 'CAC', 'CTR'], correct: 2, explanation: 'If CAC exceeds LTV, you lose money acquiring every customer.' },
      { q: 'A lead who engaged with marketing but not yet spoken to sales is called a:', options: ['SQL', 'MQL', 'CPL', 'NPS'], correct: 1, explanation: 'MQL = Marketing Qualified Lead. Once sales vets them they become an SQL.' },
    ],
    content: `## Marketing Abbreviations \u2014 From Zero to Fluent\n\nEvery paid campaign lives and dies on four numbers: CPM, CTR, CR, and ROAS.\n\n- **CPM** \u2014 cost to reach 1,000 people\n- **CTR** \u2014 percentage who clicked\n- **CR** \u2014 percentage who converted\n- **ROAS** \u2014 revenue returned per dollar spent\n\nA 2% CTR sounds good until you see a 0.5% conversion rate. A low ROAS could be a CPM, creative, landing page, or offer problem \u2014 only tracing the full funnel tells you which.\n\n### CAC and LTV\n\nCAC = Total Marketing Spend \u00f7 New Customers Acquired\n\nLTV = Average Purchase Value \u00d7 Purchase Frequency \u00d7 Customer Lifespan\n\nIf your LTV is $300 and CAC is $100, you have a 3:1 LTV/CAC ratio \u2014 generally healthy. Below 2:1 and growth is burning capital. Above 5:1 and you may be under-investing in acquisition.\n\n### The Lead Funnel\n\nMQL (engaged with marketing) \u2192 SQL (vetted by sales) \u2192 Opportunity \u2192 Closed/Won\n\nIf your MQL-to-SQL rate is under 20%, your targeting is attracting the wrong people.\n\n### ROI vs. ROAS\n\nROAS = Revenue \u00f7 Ad Spend \u2014 ignores COGS and overhead.\n\nROI = Net Profit \u00f7 Investment \u00d7 100% \u2014 accounts for all costs.\n\nA 4x ROAS on a product with 25% margins may be 0x profit ROI after product cost. Executives want ROI. Media buyers report ROAS. Know which conversation you are in.\n\n### NPS Benchmarks\n\n- World-class: 70+\n- Good: 50-70\n- Okay: 30-50\n- Warning sign: below 20\n\n### AOV Levers\n\nEvery $1 increase in AOV on 1,000 monthly orders = $1,000 more revenue with zero new acquisition cost.\n\n1. Upselling \u2014 higher tier of the same product\n2. Cross-selling \u2014 complementary products\n3. Order minimums \u2014 free shipping threshold lifts average basket`,
  },
  {
    id: 'terms-biz-m02',
    track: 'terms',
    title: 'Business & Startup Vocabulary',
    subtitle: 'Cap table \u00b7 runway \u00b7 burn \u00b7 pivot \u2014 the language of company-building',
    level: 'Basic',
    xp: 90,
    duration: 13,
    module: 2,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Own the vocabulary of business formation and startup operations so you can read a cap table, understand investor terms, and discuss company mechanics without hesitation.',
    keyTerms: [
      { term: 'Runway', definition: 'How long a company can operate before running out of cash at its current burn rate. Measured in months.' },
      { term: 'Burn Rate', definition: 'The rate at which a company spends its cash reserves. Gross burn = total monthly expenses. Net burn = expenses minus revenue.' },
      { term: 'Cap Table', definition: 'Capitalisation table. A record of who owns what in a company \u2014 founders, employees, investors \u2014 and on what terms.' },
      { term: 'Equity', definition: 'Ownership stake in a company, expressed as a percentage or number of shares. Dilutes when new shares are issued.' },
      { term: 'Dilution', definition: 'Reduction in existing shareholders ownership percentage when new shares are issued. Can be offset by pro-rata rights.' },
      { term: 'Valuation', definition: 'The estimated worth of a company. Pre-money is before new investment; post-money includes the new capital.' },
      { term: 'Term Sheet', definition: 'A non-binding document outlining the key terms of an investment deal before final legal agreements are drawn.' },
      { term: 'Pivot', definition: 'A fundamental change in business strategy, product direction, or market focus. Distinct from an iteration.' },
      { term: 'MVP', definition: 'Minimum Viable Product. The simplest version of a product that delivers value and enables learning from real users.' },
      { term: 'Bootstrap', definition: 'Building a company using only internal revenues and personal funds \u2014 without external investment.' },
      { term: 'ARR', definition: 'Annual Recurring Revenue. Total predictable revenue contracted for the next 12 months. The north-star metric for SaaS businesses.' },
      { term: 'Unit Economics', definition: 'The revenue and cost associated with a single customer or transaction. Determines whether scaling creates value or destroys it.' },
      { term: 'Moat', definition: 'A sustainable competitive advantage that makes it difficult for competitors to erode market position.' },
      { term: 'Vesting', definition: 'The process by which equity is earned over time. A 4-year vest with 1-year cliff means nothing vests until month 12.' },
      { term: 'Due Diligence', definition: 'The investigation a buyer or investor conducts before a transaction \u2014 financial, legal, technical, and operational review.' },
    ],
    quiz: [
      { q: 'A company has $300,000 in the bank and spends $50,000 per month. What is the runway?', options: ['3 months', '6 months', '10 months', '15 months'], correct: 1, explanation: 'Runway = cash / monthly burn = $300,000 / $50,000 = 6 months.' },
      { q: 'What does a cap table track?', options: ['Monthly expenses', 'Company ownership stakes', 'Customer acquisition cost', 'Product roadmap'], correct: 1, explanation: 'A cap table records who owns what in the company and on what terms.' },
      { q: 'A company is valued at $4M pre-money. An investor puts in $1M. What is the post-money valuation?', options: ['$3M', '$4M', '$5M', '$6M'], correct: 2, explanation: 'Post-money = pre-money + new investment = $4M + $1M = $5M.' },
      { q: 'A 4-year vest with 1-year cliff means:', options: ['All equity vests in year 1', 'No equity vests until end of year 1', 'Equity vests monthly from day 1', 'Equity vests annually only'], correct: 1, explanation: 'The cliff means you receive nothing until the cliff date (12 months), then the first tranche vests, and the rest vests monthly.' },
      { q: 'ARR stands for:', options: ['Average Revenue Rate', 'Annual Recurring Revenue', 'Adjusted Revenue Return', 'Acquisition Revenue Ratio'], correct: 1, explanation: 'ARR = Annual Recurring Revenue \u2014 total predictable contracted revenue for the next 12 months.' },
    ],
    content: `## Business & Startup Vocabulary\n\nThe language of company-building is precise because the stakes are precise.\n\n### The Cash Equation\n\n**Burn rate** is what you spend monthly. **Runway** is how long until the money runs out.\n\nRunway = Cash \u00f7 Monthly Net Burn\n\nIf you have $500k and burn $40k/month, your runway is 12.5 months. Most advisors say raise before you hit 6 months left. Waiting until 3 months is desperation territory.\n\n### Cap Tables and Dilution\n\nA cap table answers one question: who owns what?\n\nEarly example:\n- Founder A: 50%\n- Founder B: 30%\n- Employee pool: 20%\n\nAfter a $2M seed at $8M pre-money valuation:\n- Investors own 20% ($2M / $10M post-money)\n- Existing owners each diluted by ~20%\n\nDilution is not inherently bad \u2014 it depends whether the new capital creates more value than the ownership cost.\n\n### Valuation Mechanics\n\nPre-money: what the company is worth before investment.\nPost-money: pre-money + new investment.\n\nA $10M pre at $2M invested = $12M post, ~16.7% investor ownership.\n\n### MVP vs. Prototype\n\nAn MVP is not the smallest possible product \u2014 it is the smallest product that creates real value for a real customer. A prototype tests feasibility. An MVP tests the market.\n\n### Unit Economics Rule\n\nLTV / CAC > 3 is a basic health threshold for consumer businesses. Below 1 and you are paying to lose money at scale.`,
  },
  {
    id: 'terms-tech-m03',
    track: 'terms',
    title: 'Technology & Product Jargon',
    subtitle: 'API \u00b7 SaaS \u00b7 agile \u00b7 sprint \u2014 the tech vocabulary every operator needs',
    level: 'Basic',
    xp: 90,
    duration: 14,
    module: 3,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Speak the language of software and product development so you can communicate with engineers, evaluate technical decisions, and understand modern software architecture without a CS degree.',
    keyTerms: [
      { term: 'API', definition: 'Application Programming Interface. A defined way for two software systems to communicate. REST APIs use HTTP; the caller sends a request and receives structured data back.' },
      { term: 'SaaS', definition: 'Software as a Service. Software delivered via subscription over the internet, hosted by the provider. Users pay recurring fees instead of buying licenses.' },
      { term: 'Frontend', definition: 'The part of a software application users interact with directly \u2014 the browser interface, mobile screen, or desktop UI.' },
      { term: 'Backend', definition: 'The server-side logic, databases, and infrastructure that power an application \u2014 invisible to end users but essential.' },
      { term: 'Database', definition: 'An organised collection of data. Relational databases (SQL) use tables with structured rows; NoSQL databases handle unstructured or flexible-schema data.' },
      { term: 'Agile', definition: 'A project management philosophy prioritising iterative delivery, team collaboration, and responding to change over fixed plans.' },
      { term: 'Sprint', definition: 'A fixed time-box (usually 1-2 weeks) in which a team commits to completing a defined set of work in Agile/Scrum methodology.' },
      { term: 'Deployment', definition: 'The process of releasing software to a live environment. Can be to staging (test) or production (live users).' },
      { term: 'Repository (Repo)', definition: 'A version-controlled storage location for code. Git repos track all changes with history, branches, and merge capability.' },
      { term: 'Version Control', definition: 'A system that tracks changes to code over time, enabling rollback, parallel development, and team collaboration. Git is the dominant tool.' },
      { term: 'Latency', definition: 'The delay between a request and its response. Low latency = fast. Critical for real-time applications, payments, and user experience.' },
      { term: 'Scalability', definition: "A system's ability to handle increased load \u2014 more users, more data, more transactions \u2014 without performance degradation." },
      { term: 'Open Source', definition: 'Software with publicly available source code that anyone can inspect, modify, and distribute, often under a specific license.' },
      { term: 'Webhook', definition: 'An HTTP callback triggered automatically when a specific event occurs in one system, sending data to another system in real time.' },
      { term: 'CI/CD', definition: 'Continuous Integration / Continuous Deployment. Automating the process of testing code changes and releasing them to production reliably.' },
    ],
    quiz: [
      { q: 'What does API stand for?', options: ['Advanced Protocol Interface', 'Application Programming Interface', 'Automated Processing Integration', 'Active Process Integration'], correct: 1, explanation: 'API = Application Programming Interface \u2014 a defined contract for two systems to communicate.' },
      { q: 'The visible, user-facing part of a web application is called:', options: ['Backend', 'API', 'Frontend', 'Database'], correct: 2, explanation: 'Frontend is what users interact with. Backend is the server-side logic.' },
      { q: 'A SaaS business model charges:', options: ['One-time license fees', 'Per-API-call fees', 'Recurring subscription fees', 'Revenue share only'], correct: 2, explanation: 'SaaS = Software as a Service, delivered via subscription. Predictable recurring revenue is the defining characteristic.' },
      { q: 'What is a sprint in Agile methodology?', options: ['A full product launch', 'A fixed-length work period with committed deliverables', 'A daily standup meeting', 'A code review process'], correct: 1, explanation: 'A sprint is a time-boxed period (1-4 weeks) where the team delivers a defined set of features.' },
      { q: 'CI/CD automates:', options: ['Customer acquisition', 'Testing and releasing code changes', 'Database schema design', 'API documentation'], correct: 1, explanation: 'CI/CD = Continuous Integration / Continuous Deployment \u2014 automates code testing and release.' },
    ],
    content: `## Technology & Product Jargon\n\nYou do not need to code to understand software. You need to understand how the pieces fit.\n\n### The Stack\n\nEvery web application has layers:\n\n1. **Frontend** \u2014 what the user sees (HTML, CSS, JavaScript)\n2. **Backend** \u2014 business logic, authentication, data processing (Node, Python, Go)\n3. **Database** \u2014 where data is stored and queried (PostgreSQL, MongoDB, Supabase)\n4. **Infrastructure** \u2014 servers, hosting, CDNs (Vercel, AWS, Railway)\n\nAPIs sit between layers, letting them communicate using agreed-upon contracts.\n\n### APIs in Plain English\n\nAn API is a door with rules. You call the door with the right format, the system opens it and sends back data.\n\nREST APIs use HTTP methods: GET (read), POST (create), PUT/PATCH (update), DELETE (remove).\n\n### Agile vs. Waterfall\n\nWaterfall: plan everything, build everything, release.\nAgile: plan a bit, build a bit, release, repeat.\n\nAgile won because markets change faster than plans.\n\n### Deployment Pipeline\n\n1. Developer writes code on a feature branch\n2. CI runs automated tests\n3. Code merges to main\n4. CD deploys to staging for QA\n5. Release to production\n\nCI/CD collapses this from days/weeks to minutes.`,
  },
  {
    id: 'terms-fin-m04',
    track: 'terms',
    title: 'Finance & Investing Language',
    subtitle: 'P&L \u00b7 EBITDA \u00b7 cash flow \u00b7 valuation \u2014 read numbers like an investor',
    level: 'Masters',
    xp: 110,
    duration: 14,
    module: 4,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Interpret financial statements, understand valuation methodologies, and participate in financial conversations without pretending to understand numbers you have only heard in passing.',
    keyTerms: [
      { term: 'P&L', definition: 'Profit and Loss statement (also called Income Statement). Shows revenues, costs, and net income over a period.' },
      { term: 'EBITDA', definition: 'Earnings Before Interest, Taxes, Depreciation, and Amortisation. A proxy for operating cash profitability. Used heavily in valuation multiples.' },
      { term: 'Gross Margin', definition: 'Revenue minus cost of goods sold (COGS), expressed as a percentage of revenue. Shows how efficiently a company produces its product.' },
      { term: 'Net Margin', definition: 'Net profit divided by revenue. Shows how much of every dollar of revenue becomes actual profit after all expenses.' },
      { term: 'Cash Flow', definition: 'The net movement of cash into and out of a business. Operating cash flow measures cash generated from core business activity.' },
      { term: 'Balance Sheet', definition: "A snapshot of a company's financial position at a point in time: assets, liabilities, and equity. Assets = Liabilities + Equity." },
      { term: 'Working Capital', definition: 'Current assets minus current liabilities. Measures the short-term financial health and operational efficiency of a business.' },
      { term: 'ROE', definition: 'Return on Equity. Net income divided by shareholder equity. Shows how effectively the business uses owner capital to generate profit.' },
      { term: 'P/E Ratio', definition: 'Price-to-Earnings. Stock price divided by earnings per share. Used to assess whether a stock is relatively expensive or cheap versus earnings.' },
      { term: 'DCF', definition: 'Discounted Cash Flow. A valuation method that estimates the present value of future cash flows. The most theoretically rigorous valuation approach.' },
      { term: 'WACC', definition: 'Weighted Average Cost of Capital. The blended rate a company must earn to satisfy all its capital providers \u2014 debt and equity combined.' },
      { term: 'Liquidity', definition: 'How quickly an asset can be converted to cash without significant price impact. Cash is perfectly liquid; real estate is illiquid.' },
      { term: 'Leverage', definition: 'Using borrowed capital to amplify potential returns. Also amplifies losses. Expressed as debt-to-equity ratio.' },
      { term: 'Amortisation', definition: 'Spreading the cost of an intangible asset over its useful life. Similar to depreciation but applied to intangibles (patents, software).' },
      { term: 'Accounts Receivable', definition: 'Money owed to a company by customers for goods or services already delivered. An asset on the balance sheet.' },
    ],
    quiz: [
      { q: 'EBITDA excludes which items?', options: ['Revenue and COGS', 'Interest, taxes, depreciation, and amortisation', 'Salaries and rent', 'Marketing and sales costs'], correct: 1, explanation: 'EBITDA = Earnings Before Interest, Taxes, Depreciation, and Amortisation. Used to compare operating performance.' },
      { q: 'A company earns $1M revenue with $400k COGS. Gross margin is:', options: ['40%', '60%', '25%', '80%'], correct: 1, explanation: 'Gross margin = (Revenue - COGS) / Revenue = ($1M - $400k) / $1M = 60%.' },
      { q: 'On the balance sheet: Assets = Liabilities + ___:', options: ['Revenue', 'Equity', 'EBITDA', 'Cash Flow'], correct: 1, explanation: 'The accounting equation is always: Assets = Liabilities + Equity.' },
      { q: 'DCF stands for:', options: ['Direct Cash Flow', 'Discounted Cash Flow', 'Debt Coverage Factor', 'Dynamic Capital Formula'], correct: 1, explanation: 'DCF = Discounted Cash Flow \u2014 values a business based on the present value of expected future cash flows.' },
      { q: 'A highly liquid asset is:', options: ['Real estate', 'Restricted stock', 'Cash', 'Private equity'], correct: 2, explanation: 'Cash is perfectly liquid \u2014 instantly usable. Real estate and private equity can take months or years to convert to cash.' },
    ],
    content: `## Finance & Investing Language\n\nNumbers tell stories. You need to know how to read them.\n\n### The Three Financial Statements\n\n1. **Income Statement (P&L)**: Revenue to Gross Profit to Operating Income to Net Income\n2. **Balance Sheet**: Assets = Liabilities + Equity (point in time)\n3. **Cash Flow Statement**: Operating + Investing + Financing cash flows\n\nA company can show accounting profit and run out of cash simultaneously. Cash flow is the truth.\n\n### Gross vs. Net Margin\n\nGross margin = what you keep after producing the product.\nNet margin = what you keep after everything (salaries, rent, taxes, interest).\n\nA SaaS company with 70%+ gross margin has pricing power. A restaurant at 10% gross margin has almost no room for error.\n\n### EBITDA as a Valuation Base\n\nMost private company deals use EBITDA multiples:\n\n- Small businesses: 3-5x EBITDA\n- Mid-market: 6-10x EBITDA\n- High-growth SaaS: 15-30x ARR (revenue-based)\n\nAn operator knowing their EBITDA multiple knows their exit price.\n\n### Reading the P/E Ratio\n\nP/E of 20 means investors pay $20 for every $1 of current earnings \u2014 expecting future growth. High P/E = high expectations. When growth disappoints, high P/E stocks fall hard.\n\n### Leverage: Double-Edged\n\nDebt amplifies returns when things go well and accelerates destruction when they don't. Private equity firms buy companies at 5-8x EBITDA using 60-70% debt. If EBITDA grows, returns multiply. If it shrinks, lenders call the loan.`,
  },
  {
    id: 'terms-legal-m05',
    track: 'terms',
    title: 'Legal & Contracts Vocabulary',
    subtitle: 'NDA \u00b7 IP \u00b7 indemnity \u00b7 liability \u2014 the legal language every operator must know',
    level: 'Masters',
    xp: 100,
    duration: 13,
    module: 5,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Understand contract terms, IP rights, and legal frameworks well enough to spot problems, ask the right questions, and avoid being exploited through ignorance.',
    keyTerms: [
      { term: 'NDA', definition: 'Non-Disclosure Agreement. A contract requiring one or both parties to keep specified information confidential. Mutual NDAs bind both parties.' },
      { term: 'IP', definition: 'Intellectual Property. Legal rights over creations of the mind \u2014 patents, trademarks, copyrights, and trade secrets.' },
      { term: 'Trademark', definition: 'Legal protection for brand identifiers \u2014 names, logos, slogans \u2014 that distinguish goods or services in commerce.' },
      { term: 'Copyright', definition: 'Automatic legal protection for original creative works \u2014 writing, code, music, art. Exists at creation; registration strengthens enforcement.' },
      { term: 'Patent', definition: 'An exclusive right granted for an invention, giving the holder the right to exclude others from making, using, or selling it for a set period.' },
      { term: 'Indemnity', definition: 'A contractual obligation to compensate another party for losses or damages arising from specified events. The indemnifying party bears the risk.' },
      { term: 'Liability', definition: 'Legal responsibility for an act or omission. Limited liability (LLC, Ltd) caps personal exposure to the value invested in the business.' },
      { term: 'Arbitration', definition: 'A private dispute resolution process where a neutral arbitrator decides the outcome instead of a court judge. Often faster and cheaper than litigation.' },
      { term: 'Force Majeure', definition: 'A contract clause excusing a party from performance obligations due to extraordinary, unforeseeable events \u2014 natural disasters, pandemics, war.' },
      { term: 'Jurisdiction', definition: 'The geographic or subject-matter authority of a court or legal system to hear a case. Contracts specify which jurisdiction governs disputes.' },
      { term: 'Breach', definition: 'Failure to fulfil a contractual obligation. Material breach is significant enough to entitle the other party to terminate and seek damages.' },
      { term: 'Consideration', definition: 'Something of value exchanged between parties to make a contract legally binding. Without consideration, a promise is generally unenforceable.' },
      { term: 'Liquidated Damages', definition: 'A predetermined amount specified in a contract as compensation for a specific breach, agreed in advance rather than proven in court.' },
      { term: 'Non-Compete', definition: 'A clause preventing a party (often an employee or seller) from competing in the same market for a defined period and geography after the relationship ends.' },
      { term: 'Work for Hire', definition: 'A legal concept where IP created by an employee within the scope of employment, or certain commissioned works, belongs to the employer/commissioner.' },
    ],
    quiz: [
      { q: 'What does an NDA protect?', options: ['Physical assets', 'Confidential information', 'Patent rights', 'Employment terms'], correct: 1, explanation: 'An NDA (Non-Disclosure Agreement) legally binds parties to keep specified information confidential.' },
      { q: 'Copyright protection for an original work begins when:', options: ['You register it', 'You publish it', 'You create it', 'A lawyer files for it'], correct: 2, explanation: 'Copyright is automatic at the moment of creation \u2014 registration strengthens enforcement rights but is not required for protection to exist.' },
      { q: 'A "work for hire" clause means:', options: ['You get paid for your work', 'IP created in scope of work belongs to the employer', 'Independent contractors keep their IP', 'Work must be completed by a deadline'], correct: 1, explanation: 'Work for hire means the creator does not own the IP \u2014 the employer or commissioning party does.' },
      { q: 'Force majeure clauses excuse performance due to:', options: ['Market downturns', 'Unforeseeable extraordinary events', 'Budget constraints', 'Poor planning'], correct: 1, explanation: 'Force majeure covers events beyond reasonable control: natural disasters, pandemics, war \u2014 not poor business decisions.' },
      { q: 'A "material breach" entitles the non-breaching party to:', options: ['Only request an apology', 'Terminate the contract and seek damages', 'Nothing legally', 'Extend the contract term'], correct: 1, explanation: "A material breach \u2014 significant enough to undermine the contract's purpose \u2014 gives the aggrieved party the right to terminate and pursue damages." },
    ],
    content: `## Legal & Contracts Vocabulary\n\nYou do not need a law degree to protect yourself. You need to read what you sign.\n\n### The NDA Trap\n\nMost people sign NDAs without reading them. Key things to check:\n- **Scope**: what information is actually confidential?\n- **Duration**: 1 year? Forever?\n- **Mutual vs. one-sided**: does it bind both parties equally?\n\nA mutual NDA is standard in most business negotiations.\n\n### IP Ownership: Who Actually Owns It?\n\nIf you hire a freelancer to build your website, the default in most jurisdictions is they own the code \u2014 unless the contract says otherwise with a work-for-hire or IP assignment clause.\n\nAlways get IP assignment in writing before work begins.\n\n### Trademark vs. Copyright vs. Patent\n\n| Type | Protects | Duration |\n|------|----------|---------|\n| Trademark | Brand identifiers | Indefinite (if renewed) |\n| Copyright | Creative expression | Life + 70 years |\n| Patent | Inventions | 20 years |\n\n### Liability Structures\n\nA sole trader is personally liable for business debts. An LLC or Ltd separates personal and business liability \u2014 creditors can only reach business assets.\n\n### Reading Indemnity Clauses\n\n"Party A shall indemnify Party B from and against all claims, losses, damages arising from Party A's breach..."\n\nTranslation: if A screws up, A pays. Read who holds the indemnity in every contract you sign.`,
  },
  {
    id: 'terms-ops-m06',
    track: 'terms',
    title: 'Operations & Project Management Terms',
    subtitle: 'KPIs \u00b7 OKRs \u00b7 SOPs \u00b7 scope creep \u2014 the language of getting things done',
    level: 'Basic',
    xp: 85,
    duration: 12,
    module: 6,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Use the operational vocabulary of high-performing teams so you can build systems, set measurable targets, run projects, and communicate expectations without ambiguity.',
    keyTerms: [
      { term: 'KPI', definition: 'Key Performance Indicator. A measurable value tied to a specific objective. Effective KPIs are specific, measurable, and actionable.' },
      { term: 'OKR', definition: 'Objectives and Key Results. A goal-setting framework: the Objective is qualitative and aspirational; Key Results are measurable outcomes.' },
      { term: 'SOP', definition: 'Standard Operating Procedure. A documented, step-by-step process for completing a recurring task consistently, regardless of who performs it.' },
      { term: 'Scope Creep', definition: "The gradual expansion of a project's requirements beyond the original agreement, without corresponding adjustments to timeline or budget." },
      { term: 'Bottleneck', definition: 'A constraint that limits the throughput of an entire system. The weakest link. Fixing a non-bottleneck improves nothing.' },
      { term: 'Throughput', definition: 'The rate at which a system produces output. In manufacturing: units per hour. In software: features per sprint. In sales: deals per month.' },
      { term: 'Stakeholder', definition: "Any person or group with an interest in or affected by a project's outcome \u2014 clients, team members, executives, end users." },
      { term: 'Escalation', definition: 'Raising an issue to a higher authority when it cannot be resolved at the current level \u2014 not a failure, a process.' },
      { term: 'Deliverable', definition: 'A specific, tangible output or outcome that must be produced as part of a project \u2014 defined, measurable, and time-bound.' },
      { term: 'Milestone', definition: 'A significant checkpoint in a project that signals meaningful progress. Used to align stakeholders and trigger next phases.' },
      { term: 'Risk Register', definition: 'A documented list of identified project risks, their likelihood, potential impact, and mitigation strategies.' },
      { term: 'Retrospective', definition: "A structured review at the end of a project phase: what went well, what didn't, what to change. The foundation of continuous improvement." },
      { term: 'Capacity Planning', definition: 'Forecasting the human, time, and technical resources needed to meet project demands. Prevents over-commitment.' },
      { term: 'Bandwidth', definition: "In operations: a person's or team's available time and cognitive capacity for additional work." },
      { term: 'RACI', definition: 'Responsible, Accountable, Consulted, Informed. A matrix assigning each role in a project to clarify decision-making and avoid duplication.' },
    ],
    quiz: [
      { q: 'The difference between a KPI and an OKR is:', options: ['KPIs are qualitative; OKRs are quantitative', 'OKRs combine aspirational objectives with measurable key results', 'KPIs are set quarterly; OKRs are set daily', 'There is no practical difference'], correct: 1, explanation: 'OKRs = Objective (aspirational) + Key Results (measurable). KPIs are standalone metrics.' },
      { q: 'Scope creep happens when:', options: ['A project is delivered early', 'Project requirements expand beyond the original agreement', 'A team exceeds its budget', 'A deadline is missed'], correct: 1, explanation: 'Scope creep is gradual requirement expansion without adjusting timeline or budget.' },
      { q: 'Fixing a non-bottleneck in a system:', options: ['Dramatically improves output', 'Has no effect on overall throughput', 'Doubles capacity', 'Eliminates waste'], correct: 1, explanation: 'The Theory of Constraints: only fixing the bottleneck improves system throughput.' },
      { q: 'A RACI matrix defines:', options: ['Revenue and cost allocation', 'Who is Responsible, Accountable, Consulted, and Informed', 'Risk and contingency plans', 'Roles and compensation bands'], correct: 1, explanation: 'RACI = Responsible, Accountable, Consulted, Informed. Clarifies decision rights on every task.' },
      { q: 'An SOP ensures:', options: ['Creative freedom in execution', 'Consistent process execution regardless of who performs it', 'Projects finish ahead of schedule', 'Budgets are never exceeded'], correct: 1, explanation: 'An SOP documents a process so any qualified person follows it the same way, ensuring consistent quality.' },
    ],
    content: `## Operations & Project Management Terms\n\nSystems beat talent at scale. The operators who win are the ones who build repeatable processes.\n\n### OKRs Done Right\n\nObjective: "Become the go-to legal tech firm in Kingston by Q4."\nKey Results:\n1. 15 qualified leads from direct search (not referrals)\n2. 3 pieces of thought leadership published with 500+ reach each\n3. Net Promoter Score above 60\n\nThe Objective is motivating. The Key Results are binary \u2014 achieved or not.\n\n### SOP: The Most Underrated Asset\n\nAn SOP is worth more than a talented employee. A talented employee leaves. An SOP stays, trains the next person, and holds quality constant.\n\nFormat: Trigger, Steps, Output, Owner.\n\n### Scope Creep: The Silent Project Killer\n\n"Can you just add..." is the most expensive sentence in project management.\n\nEvery addition should go through a change request: document the change, estimate impact, get written approval before proceeding.\n\n### The Bottleneck Principle\n\nAdd three people to a non-bottleneck step and the output doesn't move. Fix the bottleneck and the whole system breathes.`,
  },
  {
    id: 'terms-creative-m07',
    track: 'terms',
    title: 'Creative Industry Language',
    subtitle: 'Briefs \u00b7 mood boards \u00b7 art direction \u00b7 copy \u2014 the vocabulary of the creative world',
    level: 'Basic',
    xp: 85,
    duration: 12,
    module: 7,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Communicate with creatives, brief designers and photographers, evaluate creative work, and navigate the creative industry without mistaking output for intention.',
    keyTerms: [
      { term: 'Creative Brief', definition: 'A document that defines the objectives, audience, tone, deliverables, and constraints for a creative project. The more precise the brief, the better the output.' },
      { term: 'Art Direction', definition: 'The discipline of guiding the visual and aesthetic decisions of a project \u2014 composition, colour, typography, photography, motion.' },
      { term: 'Mood Board', definition: 'A visual collage of reference images, colours, typography, and textures used to communicate aesthetic direction before production begins.' },
      { term: 'Copywriting', definition: 'The craft of writing persuasive content designed to move audiences to action. Distinct from content writing, which informs rather than converts.' },
      { term: 'Typography', definition: 'The art and technique of arranging type \u2014 font choice, size, weight, spacing, and hierarchy \u2014 to communicate effectively and aesthetically.' },
      { term: 'Colour Theory', definition: 'The study of how colours interact, combine, and communicate meaning. Includes the colour wheel, complementary/analogous palettes, and psychological associations.' },
      { term: 'White Space', definition: 'The empty space between design elements. Not dead space \u2014 it provides breathing room, hierarchy, and focus. Premium brands use more of it.' },
      { term: 'Brand Identity', definition: 'The visual and verbal elements that distinguish a brand \u2014 logo, colours, typography, voice, and tone \u2014 and how they are applied consistently.' },
      { term: 'Wireframe', definition: 'A low-fidelity structural layout of a page or screen showing content placement and hierarchy without visual design decisions.' },
      { term: 'Mockup', definition: 'A static, high-fidelity visual representation of a final design \u2014 realistic in appearance but not functional.' },
      { term: 'Storyboard', definition: 'A sequence of illustrated or described frames showing how a video, animation, or interactive experience will unfold scene by scene.' },
      { term: 'Asset', definition: 'Any production-ready file used in a creative project \u2014 images, logos, fonts, icons, videos, copy files.' },
      { term: 'Iteration', definition: 'A revised version of a creative work, incorporating feedback. Professional creative process involves multiple iterations before finalisation.' },
      { term: 'Spec Work', definition: 'Creative work produced without guarantee of payment or approval, typically as part of a pitch. Widely considered exploitative of creative professionals.' },
      { term: 'Kerning', definition: 'The adjustment of spacing between specific pairs of letters to achieve visually balanced and readable text.' },
    ],
    quiz: [
      { q: "A creative brief's primary purpose is to:", options: ["List the client's budget", 'Define objectives, audience, tone, and deliverables upfront', 'Approve final designs', 'Track project timelines'], correct: 1, explanation: 'A brief eliminates ambiguity before work begins \u2014 the more precise, the less revision required.' },
      { q: 'White space in design primarily:', options: ['Saves printing costs', 'Creates hierarchy and breathing room', 'Is used when content is missing', 'Indicates premium pricing'], correct: 1, explanation: 'White space is intentional \u2014 it focuses attention and communicates confidence. Cluttered design signals amateur work.' },
      { q: 'The difference between a wireframe and a mockup is:', options: ['Wireframes are digital; mockups are printed', 'Wireframes show structure; mockups show finished visual design', 'Mockups are rough; wireframes are final', 'They are the same thing'], correct: 1, explanation: 'A wireframe is structural/low-fidelity. A mockup is visual/high-fidelity. A prototype adds interactivity.' },
      { q: 'Art direction is the discipline of:', options: ['Writing advertising copy', 'Guiding the visual and aesthetic decisions of a project', 'Managing creative budgets', 'Building brand identities only'], correct: 1, explanation: 'Art direction covers all visual decision-making: composition, photography, colour, layout, motion.' },
      { q: 'Copywriting differs from content writing in that copywriting is:', options: ['Always longer form', 'Designed to persuade and drive action', 'Only used in print', 'Written by journalists'], correct: 1, explanation: 'Copywriting converts. Content writing informs.' },
    ],
    content: `## Creative Industry Language\n\nThe best creative work is not accidental. It follows a vocabulary and a process.\n\n### The Brief Is Everything\n\nStrong brief components:\n1. **Objective**: what should this piece accomplish?\n2. **Audience**: who specifically is this for?\n3. **Tone**: 3-5 adjectives (confident, irreverent, warm \u2014 never "professional")\n4. **Mandatory elements**: logo usage, colours, legal disclaimers\n5. **What to avoid**: competitors, associations, aesthetics\n\n### Hierarchy of Visual Communication\n\n1. **Colour** \u2014 noticed first\n2. **Form/shape** \u2014 processed second\n3. **Typography** \u2014 read third\n4. **Content** \u2014 understood last\n\nPoor design reverses this. Premium design aligns it.\n\n### Mood Boards: Aligning Before Creating\n\nA mood board aligned three stakeholders before $50,000 of production spends is worth more than three rounds of revisions after.\n\n### Copywriting Fundamentals\n\nThe hierarchy of persuasion:\n- **Headline**: earns the read\n- **Subheadline**: promises specifics\n- **Body**: delivers the proof\n- **CTA**: removes friction from the action`,
  },
  {
    id: 'terms-social-m08',
    track: 'terms',
    title: 'Social Media & Content Terms',
    subtitle: 'Algorithm \u00b7 reach \u00b7 impressions \u00b7 engagement rate \u2014 the metrics that matter',
    level: 'Basic',
    xp: 85,
    duration: 12,
    module: 8,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Interpret social media analytics, understand platform algorithms, and make informed content decisions using the vocabulary of the platforms that now govern commercial attention.',
    keyTerms: [
      { term: 'Algorithm', definition: 'The automated system platforms use to decide what content to show users. Factors include engagement rate, watch time, relationship strength, and relevance signals.' },
      { term: 'Reach', definition: 'The number of unique accounts that saw a piece of content in a given period. Organic reach (unpaid) vs. paid reach.' },
      { term: 'Impressions', definition: 'The total number of times content was displayed, including multiple views by the same user. Impressions are always greater than or equal to Reach.' },
      { term: 'Engagement Rate', definition: 'Total engagements (likes, comments, shares, saves) divided by reach or follower count. The most honest measure of content resonance.' },
      { term: 'Share of Voice', definition: "Your brand's presence in a conversation or market relative to competitors. High share of voice in a category signals authority." },
      { term: 'Organic', definition: 'Content that reaches audiences without paid promotion. Organic reach has declined on most platforms as they monetise attention.' },
      { term: 'Paid Media', definition: 'Content amplified through purchased advertising. Predictable, scalable, but stops when budget stops.' },
      { term: 'Earned Media', definition: 'Coverage or amplification you receive without paying for it \u2014 press mentions, shares, word-of-mouth. The most credible form.' },
      { term: 'Content Pillar', definition: 'A core theme or topic a brand consistently creates content around, building recognisable territory and category ownership.' },
      { term: 'Hook', definition: 'The first 1-3 seconds of a video or first line of a caption that determines whether an audience keeps watching or scrolls past.' },
      { term: 'Save Rate', definition: 'Saves divided by reach. A high save rate signals content that audiences find genuinely valuable enough to retrieve later \u2014 a strong quality signal.' },
      { term: 'Dark Social', definition: 'Traffic or sharing that occurs in private channels \u2014 WhatsApp, DMs, email \u2014 that analytics cannot track. Underrated and underreported.' },
      { term: 'UGC', definition: 'User-Generated Content. Content created by your audience, customers, or community about your brand. High trust, low cost, difficult to manufacture.' },
      { term: 'CTR (Content)', definition: 'Click-Through Rate in content context: percentage of people who clicked a link or CTA from the content piece.' },
      { term: 'Conversion (Social)', definition: 'A desired action taken after engaging with social content \u2014 clicking a link, signing up, purchasing.' },
    ],
    quiz: [
      { q: 'Impressions differ from reach because impressions:', options: ['Count only unique viewers', 'Include multiple views by the same user', 'Measure only paid exposure', 'Are always lower than reach'], correct: 1, explanation: 'Reach = unique accounts. Impressions = total displays including repeated views.' },
      { q: 'A high save rate on a post signals:', options: ['Low engagement quality', 'Content audiences found genuinely valuable', 'Platform promotion', 'Viral spread'], correct: 1, explanation: 'Saves indicate intent to return to content \u2014 a stronger quality signal than likes, which are reflexive.' },
      { q: 'Earned media is:', options: ['Paid advertising', 'Owned website content', 'Coverage received without payment \u2014 press, shares, word-of-mouth', 'Sponsored posts'], correct: 2, explanation: 'Earned media is organic third-party amplification. It is the most credible because it is not purchased.' },
      { q: 'Dark social refers to:', options: ['Negative brand mentions', 'Private sharing that analytics cannot track', 'Deleted posts', 'Shadow banning'], correct: 1, explanation: 'Dark social = sharing via private channels (WhatsApp, DMs, email) that attribution tools cannot measure.' },
      { q: 'Engagement rate is calculated as:', options: ['Followers / Impressions', 'Total Engagements / Reach or Followers', 'Comments / Likes', 'Reach / Impressions'], correct: 1, explanation: 'Engagement rate = (Likes + Comments + Shares + Saves) / Reach (or Followers).' },
    ],
    content: `## Social Media & Content Terms\n\nAttention is the asset. Understanding how it moves is the leverage.\n\n### How Algorithms Actually Work\n\nAlgorithms are distribution machines optimising for platform retention. They surface content that:\n1. Gets watched/read longer (watch time, read time)\n2. Gets meaningful responses (comments, shares, saves > likes)\n3. Gets people to come back to the platform\n\n### The Reach / Engagement Paradox\n\nAs follower counts grow, organic reach typically falls as a percentage. A 50,000-follower account might reach 3-5% organically. A 5,000-follower account with high engagement might reach 25%.\n\nEngagement rate is the metric that matters, not follower count.\n\n### The Three Media Types\n\n| Type | Example | Control | Trust | Cost |\n|------|---------|---------|-------|------|\n| Paid | Facebook Ad | High | Low | $$ |\n| Owned | Your Website | Total | Medium | Low |\n| Earned | Press Feature | None | High | 0 |\n\n### Content Pillars: Own a Territory\n\nPick 3-5 topics you will become known for. Consistency beats novelty. The algorithm rewards accounts it can categorise.`,
  },
  {
    id: 'terms-ai-m09',
    track: 'terms',
    title: 'AI & Data Vocabulary',
    subtitle: 'LLMs \u00b7 embeddings \u00b7 RAG \u00b7 tokens \u2014 the language of the AI era',
    level: 'PhD',
    xp: 130,
    duration: 15,
    module: 9,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Understand AI and data terminology at a working level \u2014 enough to direct AI product decisions, brief engineers, evaluate AI tools, and not be misled by marketing language.',
    keyTerms: [
      { term: 'LLM', definition: 'Large Language Model. An AI system trained on vast text data to predict and generate language. GPT-4, Claude, Gemini are LLMs.' },
      { term: 'Token', definition: 'The unit LLMs process text in \u2014 roughly a word or word fragment. Pricing, context windows, and generation speed are all measured in tokens.' },
      { term: 'Context Window', definition: 'The maximum amount of text an LLM can process in a single conversation \u2014 both input and output. Larger windows enable longer, more complex tasks.' },
      { term: 'Prompt', definition: 'The input text (instruction, question, context) sent to an LLM. Prompt engineering is the craft of structuring inputs to get better outputs.' },
      { term: 'Embedding', definition: 'A numerical vector representation of text (or other data) that captures semantic meaning. Similar concepts have vectors close together in high-dimensional space.' },
      { term: 'RAG', definition: 'Retrieval-Augmented Generation. A technique where an AI retrieves relevant information from a knowledge base before generating a response, grounding answers in specific data.' },
      { term: 'Fine-tuning', definition: 'Training a pre-trained model further on a specific dataset to adapt its behaviour for a particular task or domain.' },
      { term: 'Hallucination', definition: 'When an LLM confidently generates factually incorrect information. Not a glitch \u2014 a structural feature of probabilistic generation.' },
      { term: 'Temperature', definition: 'A parameter controlling LLM output randomness. Low temperature = deterministic/predictable. High temperature = creative/varied.' },
      { term: 'Vector Database', definition: 'A database optimised for storing and querying embedding vectors \u2014 enabling semantic search rather than exact-match search.' },
      { term: 'Dataset', definition: 'A structured collection of data used to train, validate, or test a machine learning model. Quality, size, and diversity of data determine model capability.' },
      { term: 'Inference', definition: 'The process of using a trained AI model to generate outputs from new inputs. Training creates the model; inference is using it.' },
      { term: 'Agent', definition: 'An AI system that can take actions, use tools, and make sequential decisions to complete multi-step tasks autonomously.' },
      { term: 'Multimodal', definition: 'An AI model capable of processing multiple types of input \u2014 text, images, audio, video \u2014 within the same system.' },
      { term: 'Zero-shot', definition: 'Asking a model to perform a task without providing any examples. Few-shot provides a small number of examples to guide the format or approach.' },
    ],
    quiz: [
      { q: 'An LLM "hallucination" refers to:', options: ['Visual image generation errors', 'Confidently generated factually incorrect information', 'A model that refuses requests', 'Slow response times'], correct: 1, explanation: 'Hallucination is when an LLM generates plausible-sounding but false information with high confidence \u2014 a structural consequence of probabilistic generation.' },
      { q: 'RAG stands for:', options: ['Real-time AI Generation', 'Retrieval-Augmented Generation', 'Recursive Algorithmic Grounding', 'Ranked Answer Generation'], correct: 1, explanation: 'RAG retrieves relevant information before generating a response \u2014 grounding AI answers in specific, verifiable data.' },
      { q: 'A higher "temperature" setting in an LLM produces:', options: ['Faster responses', 'More deterministic outputs', 'More varied/creative outputs', 'Shorter responses'], correct: 2, explanation: 'High temperature increases randomness/creativity. Low temperature makes the model more predictable.' },
      { q: 'Embeddings are used for:', options: ['Speed optimisation', 'Semantic search \u2014 finding conceptually similar content', 'Reducing hallucinations', 'Training data labelling'], correct: 1, explanation: 'Embeddings map text to vectors where semantic similarity = vector proximity. This enables "find content similar to this" queries.' },
      { q: 'Fine-tuning a model means:', options: ['Adjusting the temperature parameter', 'Training a pre-trained model further on specific data', 'Writing better prompts', 'Reducing model size'], correct: 1, explanation: 'Fine-tuning continues training on a new dataset \u2014 adapting a general model to a specific domain or behaviour.' },
    ],
    content: `## AI & Data Vocabulary\n\nAI is not magic. It is statistics at scale with a very good user interface.\n\n### How LLMs Actually Work\n\nAn LLM is a next-token predictor. Trained on billions of documents, it learns the statistical patterns of language \u2014 what word follows what, in what contexts.\n\nWhen you send a prompt, the model generates tokens one at a time, each based on the probability distribution of what comes next given everything before it.\n\nThis is why hallucinations happen. The model does not "know" things \u2014 it predicts plausible text. Sometimes plausible is wrong.\n\n### The Token Economy\n\nEverything in LLM APIs is measured in tokens:\n- Input tokens (your prompt)\n- Output tokens (the response)\n- Context window (max tokens in one call)\n\nA 200,000-token context window means you can send an entire book in one call.\n\n### RAG: Grounding AI in Your Data\n\nWithout RAG: "What are our Q3 sales?" \u2014 hallucination.\nWith RAG: retrieve Q3 sales data from database \u2014 generate answer grounded in real data.\n\nRAG architecture:\n1. Chunk and embed your knowledge base\n2. Store vectors in a vector database\n3. Query: embed the user question, find similar chunks, inject into prompt\n4. LLM generates with real context\n\n### Agents: AI That Acts\n\nAn agent is an LLM with tools: search the web, query a database, send an email, write and run code. Multi-step tasks that previously required hours of human work become automated loops.`,
  },
  {
    id: 'terms-gamedev-m10',
    track: 'terms',
    title: 'Game Design & Dev Terms',
    subtitle: 'Mechanics \u00b7 loops \u00b7 procedural generation \u00b7 assets \u2014 the vocabulary of game creation',
    level: 'Masters',
    xp: 100,
    duration: 12,
    module: 10,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Understand the language of game design and development well enough to brief a game team, evaluate design decisions, and discuss mechanics without reducing everything to "gameplay."',
    keyTerms: [
      { term: 'Game Mechanic', definition: 'A rule or system governing player interaction. Mechanics are what players do repeatedly \u2014 jump, shoot, collect, trade. Good mechanics are learnable but deep.' },
      { term: 'Core Loop', definition: "The central, repeating cycle of player actions and rewards that defines the game's fundamental rhythm. Kill, loot, upgrade, repeat." },
      { term: 'Meta-game', definition: 'The strategy layer above individual sessions \u2014 how players optimise across many plays. A game with no meta has low long-term retention.' },
      { term: 'Procedural Generation', definition: 'Using algorithms to generate game content (levels, items, worlds) dynamically rather than hand-crafting every element. Enables replayability.' },
      { term: 'Sprite', definition: 'A 2D image or animation used in a game. Characters, tiles, effects, and UI elements are typically sprites in 2D game development.' },
      { term: 'Hitbox', definition: 'The invisible collision boundary around a game object used to detect when it makes contact with another object. Tight hitboxes feel fair; loose ones feel unfair.' },
      { term: 'Game Feel', definition: 'The tactile quality of interaction \u2014 how responsive, satisfying, and right controls and feedback feel. Difficult to define, immediately noticeable when absent.' },
      { term: 'Progression System', definition: 'The structured path of character, ability, or content unlocks that motivates continued play and rewards investment over time.' },
      { term: 'Game Economy', definition: 'The system of resources, currencies, production, and consumption within a game. Balancing economy prevents inflation, hoarding, or scarcity collapse.' },
      { term: 'Narrative Design', definition: 'The craft of integrating story, lore, and character into gameplay systems \u2014 not just cutscenes, but world-building through mechanics and environment.' },
      { term: 'Game Engine', definition: 'A software framework providing the tools to build a game \u2014 rendering, physics, audio, input, scripting. Phaser, Unity, Unreal, Godot are examples.' },
      { term: 'Shader', definition: 'A small program running on the GPU that determines how pixels are rendered \u2014 controlling lighting, shadows, colour effects, and visual style.' },
      { term: 'Latency (Game)', definition: 'The delay between player input and on-screen response. Over 100ms latency in action games is perceptible and degrades experience.' },
      { term: 'Playtesting', definition: 'Structured testing of a game by real players to identify friction, confusion, difficulty spikes, and unexpected behaviour before release.' },
      { term: 'UX (Game)', definition: 'User Experience in a game context: tutorial design, menu clarity, onboarding, controller feedback \u2014 reducing friction in how players learn and navigate.' },
    ],
    quiz: [
      { q: 'The "core loop" in a game refers to:', options: ['The main storyline', 'The central repeating cycle of player action and reward', 'The tutorial sequence', 'The final boss encounter'], correct: 1, explanation: 'Core loop = the fundamental rhythm of what players do repeatedly.' },
      { q: 'Procedural generation is used to:', options: ['Manually design every level', 'Algorithmically create content for variety and replayability', 'Program enemy AI', 'Optimise game performance'], correct: 1, explanation: 'Procedural generation uses algorithms to create content dynamically \u2014 enabling infinite variation in levels, items, or worlds.' },
      { q: '"Game feel" refers to:', options: ["The game's story quality", 'How responsive and satisfying controls and feedback feel', 'Graphics quality', 'Level of difficulty'], correct: 1, explanation: 'Game feel is the tactile, responsive quality of interaction. Hard to define; immediately noticeable when missing.' },
      { q: 'A hitbox is:', options: ['A health system', 'The invisible collision boundary for detecting contact', 'The damage value of an attack', "The player's inventory"], correct: 1, explanation: 'Hitboxes define physical boundaries for collision detection. Tight hitboxes = fair. Loose = frustrating.' },
      { q: 'The meta-game is:', options: ["The game's storyline", 'Strategy optimised across many sessions \u2014 long-term player optimisation', 'The tutorial mode', 'The hidden difficulty mode'], correct: 1, explanation: 'The meta-game is what players optimise over time across many sessions \u2014 deck builds, tier lists, optimal strategies. It drives retention.' },
    ],
    content: `## Game Design & Dev Terms\n\nEvery game you have ever played is a system. Once you see the systems, you cannot unsee them.\n\n### The Core Loop Governs Everything\n\nEvery successful game has a loop players want to repeat:\n- **Shooter**: engage, eliminate, loot, upgrade\n- **RPG**: explore, fight, level up, explore more\n- **Puzzle**: see problem, experiment, solve, feel clever\n\nThe loop must be satisfying at the micro-level (individual interactions) and the macro-level (session to session).\n\n### Game Feel: The Invisible Quality\n\nGame feel is what separates a technically functional game from one that players describe as "juicy" or "tight." It comes from:\n- Input latency (under 16ms is imperceptible)\n- Visual feedback (particles, screen shake, flash)\n- Sound design (hits that sound impactful)\n- Camera response (follows action with the right weight)\n\nAdd screen shake to a jump. Immediately feels better. This is not a graphic \u2014 it is physics.\n\n### Procedural Generation vs. Handcrafted Design\n\n| Approach | Replayability | Control | Dev Cost |\n|----------|--------------|---------|----------|\n| Procedural | Very high | Low | Medium |\n| Handcrafted | Low | Very high | High |\n\nMost modern indie games combine both: procedural structure + handcrafted content nodes.\n\n### Economy Design Mistakes\n\n1. Inflation: players accumulate so much currency it loses meaning\n2. Scarcity collapse: essential items too rare to find normally\n3. Pay-to-win: real money buys power, not cosmetics\n\nA healthy game economy feels like challenge, not grind.`,
  },
  {
    id: 'terms-trade-m11',
    track: 'terms',
    title: 'Global Commerce & Trade Terms',
    subtitle: 'FX \u00b7 Incoterms \u00b7 remittance \u00b7 duties \u2014 the vocabulary of cross-border business',
    level: 'Masters',
    xp: 100,
    duration: 13,
    module: 11,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Operate across borders with commercial fluency \u2014 understanding foreign exchange, trade terms, banking instruments, and the regulatory vocabulary of international commerce.',
    keyTerms: [
      { term: 'FX', definition: 'Foreign Exchange. The global market for trading currencies. The FX rate between two currencies determines the relative value of cross-border transactions.' },
      { term: 'Incoterms', definition: 'International Commercial Terms. Standardised trade terms (published by the ICC) defining who bears risk and cost at each stage of an international shipment.' },
      { term: 'FOB', definition: 'Free on Board. An Incoterm where risk passes from seller to buyer when goods are loaded onto the vessel. Buyer assumes freight and insurance from that point.' },
      { term: 'CIF', definition: 'Cost, Insurance, and Freight. Seller pays for goods, insurance, and freight to the destination port. Risk transfers to buyer when goods arrive.' },
      { term: 'Letter of Credit', definition: 'A bank-issued document guaranteeing payment to a seller upon presentation of specified documents. Eliminates counterparty risk in international trade.' },
      { term: 'Duty', definition: 'A tax imposed by a government on imported or exported goods. Ad valorem duties are percentage-based; specific duties are per-unit.' },
      { term: 'Tariff', definition: 'A government-imposed tax on imports, typically used to protect domestic industries or as a trade policy tool.' },
      { term: 'Customs Clearance', definition: 'The process of obtaining government permission for goods to enter or leave a country \u2014 paying duties, providing documentation, passing inspection.' },
      { term: 'Remittance', definition: 'Money transferred to another country, typically by a worker to their family. A major economic flow for developing nations \u2014 Jamaica receives approximately $3B annually.' },
      { term: 'Exchange Rate', definition: 'The price of one currency expressed in another. A USD/JMD rate of 157 means 1 US dollar buys 157 Jamaican dollars.' },
      { term: 'Arbitrage', definition: 'Profiting from price differences for the same asset in different markets. In FX: simultaneously buying and selling the same currency pair to exploit rate gaps.' },
      { term: 'SWIFT', definition: 'Society for Worldwide Interbank Financial Telecommunication. The messaging network banks use to send international payment instructions securely.' },
      { term: 'Free Trade Zone', definition: 'A geographic area where goods may be imported, manufactured, and re-exported with reduced or zero customs duties. Used to attract investment and manufacturing.' },
      { term: 'Bill of Lading', definition: 'A legal document issued by a carrier acknowledging receipt of goods for shipment. Serves as a receipt, contract of carriage, and title document.' },
      { term: 'Hedging', definition: 'Using financial instruments (options, forwards, futures) to reduce or offset exposure to currency, commodity, or interest rate risk.' },
    ],
    quiz: [
      { q: 'Under FOB terms, risk transfers to the buyer when:', options: ['The order is placed', 'Goods are loaded onto the vessel at origin', 'Goods arrive at destination port', 'The invoice is paid'], correct: 1, explanation: 'FOB = Free on Board. Seller delivers to port and loads. Once aboard, risk (and cost) shifts to buyer.' },
      { q: 'A Letter of Credit primarily protects:', options: ['The shipping carrier', 'The seller against non-payment risk', "The buyer's customs agent", 'The freight forwarder'], correct: 1, explanation: "A letter of credit guarantees payment to the seller by the buyer's bank \u2014 once the seller presents complying documents, payment is certain." },
      { q: 'Remittance refers to:', options: ['Bank-to-bank wire transfers between corporations', 'Money sent by workers to family in another country', 'Import duty payments', 'Currency exchange transactions'], correct: 1, explanation: 'Remittances are personal money transfers \u2014 typically migrant workers sending money home.' },
      { q: 'Incoterms define:', options: ['Tax rates on imports', 'Risk and cost responsibility at each stage of international shipment', 'SWIFT payment codes', 'Currency conversion rates'], correct: 1, explanation: 'Incoterms are standardised definitions of who bears risk and pays costs at each stage of a cross-border shipment.' },
      { q: 'Hedging in international business is used to:', options: ['Maximise currency speculation profits', 'Reduce or offset exposure to currency or price risk', 'Avoid paying import duties', 'Bypass SWIFT messaging'], correct: 1, explanation: 'Hedging uses financial instruments to lock in rates or prices \u2014 protecting against unfavourable movements in currency, interest, or commodity markets.' },
    ],
    content: `## Global Commerce & Trade Terms\n\nThe world trades $32 trillion annually. The vocabulary of that trade is a professional language.\n\n### Incoterms: Who Owns the Risk?\n\n- **EXW** (Ex Works): Buyer picks up from seller warehouse. Maximum buyer responsibility.\n- **FOB**: Seller loads vessel. Risk transfers on loading.\n- **CIF**: Seller arranges freight and insurance to destination port.\n- **DDP** (Delivered Duty Paid): Seller handles everything including destination duties. Maximum seller responsibility.\n\nKnowing the Incoterm in a contract tells you exactly where your responsibility begins and ends.\n\n### FX Risk in Cross-Border Business\n\nIf you invoice in USD but earn in JMD, a 5% depreciation of JMD costs you 5% of gross margin \u2014 before any business expenses.\n\nOptions:\n1. Invoice in your home currency (shift risk to buyer)\n2. Forward contract (lock in exchange rate now for future delivery)\n3. Natural hedge (earn and spend in the same currency)\n\n### The Letter of Credit Mechanism\n\nLC steps:\n1. Buyer applies for LC at their bank\n2. Bank issues LC to seller\n3. Seller ships and presents complying documents\n4. Bank pays \u2014 regardless of buyer's financial condition\n\nCritical in emerging-market trade where counterparty trust is limited.\n\n### Remittance: The Hidden Economic Force\n\nJamaica's remittance inflows (~$3B USD annually) exceed FDI and tourism combined in some years. Understanding remittance flows matters for anyone in JA commerce.`,
  },
  {
    id: 'terms-jargon-m12',
    track: 'terms',
    title: 'The Jargon Trap \u2014 Words That Mislead',
    subtitle: 'Synergy \u00b7 disruption \u00b7 scalable \u00b7 leverage \u2014 the terms smart people abuse',
    level: 'Masters',
    xp: 110,
    duration: 13,
    module: 12,
    certArea: 'Common Terms & Systems',
    courseObjective: 'Identify hollow jargon, decode what speakers actually mean, and replace performance vocabulary with precise language that communicates rather than signals.',
    keyTerms: [
      { term: 'Synergy', definition: 'Originally: the combined effect exceeding the sum of parts. In practice: a filler word used in M&A pitches and strategy decks to avoid saying what actually happens.' },
      { term: 'Disruption', definition: "Clayton Christensen's term for a specific mechanism where simpler, cheaper products eventually displace established ones. Now misused to mean any new product or competitor." },
      { term: 'Scalable', definition: 'A system that handles increased load without proportional cost increases. Misused as a generic compliment to mean "we want to do less work."' },
      { term: 'Leverage', definition: 'Using a resource, relationship, or position to achieve a disproportionate outcome. Misused to mean simply "use."' },
      { term: 'Pivot', definition: 'A strategic change in direction based on validated learning. Misused as an excuse for any failed initiative or random change without data.' },
      { term: 'Ecosystem', definition: 'A network of interacting organisations and stakeholders. Misused to make simple business relationships sound complex and defensible.' },
      { term: 'Holistic', definition: 'Considering a whole system and its interconnections. Misused to mean "we will think about multiple things" without specifying what or how.' },
      { term: 'Value-add', definition: 'A genuine increase in value at a specific step. Misused as a reflexive modifier for standard vendor relationships.' },
      { term: 'Best-in-class', definition: 'Superior to all alternatives in a category, with measurable evidence. Misused as self-promotional language without any comparative data.' },
      { term: 'Thought Leadership', definition: 'Demonstrably advancing understanding of a topic through original research or insight. Misused to mean publishing any content at all.' },
      { term: 'Bandwidth', definition: "Available capacity. Misused as a polite refusal mechanism: \"I don't have bandwidth\" almost always means \"I choose not to prioritise this.\"" },
      { term: 'Move the Needle', definition: 'Make a meaningful, measurable difference. Usually said in contexts where no actual measurement is planned or will occur.' },
      { term: 'Optics', definition: 'How a situation appears to others. Legitimate in communications strategy. Misused to make superficial impression management sound strategic.' },
      { term: 'Agile', definition: 'A specific project management methodology with defined ceremonies and principles. Misused to mean "we work quickly and informally without documentation."' },
      { term: 'Double-click', definition: 'Business slang for "let\'s examine this more closely." Overused in consulting to fill time without specifying what to examine.' },
    ],
    quiz: [
      { q: '"Synergy" in its original, legitimate use means:', options: ['Cost savings from mergers', 'Combined effect exceeding sum of parts', 'Partnership agreements', 'Shared infrastructure'], correct: 1, explanation: "True synergy = 1+1=3. Two businesses whose combined value exceeds what they'd create separately. Most M&A synergies are announced and never materialise." },
      { q: "Clayton Christensen's definition of disruption is specifically about:", options: ['Any new competitive product', 'Simpler/cheaper products that eventually displace established ones from below', 'Technology replacing human labour', 'Any fast-growing startup'], correct: 1, explanation: "Disruption describes a specific market mechanism \u2014 entrants start at low-end/non-consumption and move upmarket." },
      { q: '"I don\'t have bandwidth for that" most often means:', options: ['Technical capacity is full', 'I choose not to prioritise this', 'The project requires more resources', 'Internet connectivity is insufficient'], correct: 1, explanation: 'Bandwidth as a capacity excuse is usually a prioritisation decision framed as a capacity constraint.' },
      { q: 'Which sentence uses "leverage" correctly?', options: ['"Let\'s leverage our network to get more sales."', '"The company used financial leverage to amplify returns on the acquisition."', '"We can leverage this opportunity."', '"Leverage the synergies across our ecosystem."'], correct: 1, explanation: '"Financial leverage" describes using debt to amplify returns \u2014 the technically correct use.' },
      { q: 'The jargon trap is dangerous because:', options: ['It makes presentations longer', 'It performs expertise while communicating nothing specific', 'It confuses international audiences', 'It is grammatically incorrect'], correct: 1, explanation: 'Jargon signals membership in a group while avoiding the accountability of specific claims.' },
    ],
    content: `## The Jargon Trap \u2014 Words That Mislead\n\nEvery industry develops a vocabulary. Some of it is precise and necessary. Some of it is noise designed to perform confidence without claiming anything specific.\n\n### Why Jargon Spreads\n\nJargon persists because:\n1. It signals insider status (you know the vocabulary)\n2. It provides plausible deniability (vague claims cannot be wrong)\n3. It fills time in presentations while sounding authoritative\n4. Senior people use it, so junior people imitate it\n\nThe trap: the more jargon you use, the less you communicate \u2014 and the more you reveal that you are performing rather than thinking.\n\n### The Specificity Test\n\nReplace any jargon with a specific sentence. If you cannot, you did not have a thought.\n\n| Jargon | Specific version |\n|--------|------------------|\n| "Create synergies" | "Combine the two sales teams to eliminate $800k in duplicate costs" |\n| "Move the needle" | "Increase conversion rate from 1.2% to 2.0% by October" |\n| "Leverage our network" | "Ask five specific people for warm introductions to the five specific targets" |\n| "Best-in-class" | "Ranked #1 in independent customer satisfaction surveys in our category" |\n\nIf the specific version sounds less impressive, it is also more honest and more useful.\n\n### The Disruption Misuse\n\nWhat people call disruption now: a startup that grew fast in an existing market.\n\nChristensen's original: entrant targets over-served or non-consumption segment, offers simpler cheaper product, incumbents ignore it, entrant improves over time and moves upmarket, incumbent loses market share before realising the threat.\n\n### Precision as Competitive Advantage\n\nWhen everyone around you speaks in abstractions, speaking precisely is immediately distinguishing. Specific claims get remembered, actioned, and measured. Abstract claims disappear.\n\nTrain yourself to ask: "What exactly does this mean? What would we do differently? How would we know if it worked?"`,
  },
]
