import type { VercelSiteCategory, VercelSiteEntry } from "@/lib/vercel-portfolio/types";

/**
 * Pinned site catalog — synced to the real Vercel team
 * (team_OvCeLYYttwt9SMpreFi8Fns5 / jordan-sketch-hues-projects) on 2026-06-02
 * from the Vercel API. URLs are the canonical production domain per project
 * (custom domain where one is attached, else the project's clean alias — both
 * verified, since some aliases are non-obvious e.g. wander → wander-henna).
 *
 * This is the source of truth WITHOUT a runtime token. Once VERCEL_ACCESS_TOKEN
 * is set, build-hub also auto-merges anything here with the live API and pulls
 * in any new projects automatically (no edits needed).
 */
export const VERCEL_SITE_CATEGORIES: VercelSiteCategory[] = [
  {
    id: "internal",
    label: "Internal & OS",
    description: "Your operating system, corporate sites, and conglomerate tools.",
    order: 0,
  },
  {
    id: "clients",
    label: "Client deliverables",
    description: "Sites shipped for roster clients and pipeline work.",
    order: 10,
  },
  {
    id: "products",
    label: "Product & venture builds",
    description: "J Supreme's own product platforms, venture sites, and full-stack demos.",
    order: 20,
  },
  {
    id: "experiments",
    label: "Experiments",
    description: "Spikes, promo microsites, and work-in-progress.",
    order: 30,
  },
  {
    id: "vercel-sync",
    label: "On Vercel (auto)",
    description: "Projects discovered live from your Vercel account (not pinned above).",
    order: 90,
  },
];

export const VERCEL_SITE_CATALOG: Omit<VercelSiteEntry, "source">[] = [
  // ---------------------------------------------------------------- Internal
  {
    id: "j-supreme-conglomerate",
    name: "J Supreme Conglomerate",
    url: "https://jsupremeconglomerate.online",
    description: "CRM, pipeline intake, budgeting, site kit, trading bridge — this app.",
    categoryId: "internal",
    tags: ["crm", "nextjs", "production"],
    featured: true,
    vercelProjectName: "j-supreme-conglomerate",
  },
  {
    id: "j-supreme-conglomerate-security-crm",
    name: "J Supreme Security CRM",
    url: "https://j-supreme-conglomerate-security-crm.vercel.app",
    description: "Separate security-services CRM (distinct from the main conglomerate OS).",
    categoryId: "internal",
    tags: ["crm", "nextjs", "security"],
    vercelProjectName: "j-supreme-conglomerate-security-crm",
  },
  {
    id: "supreme-suite",
    name: "Supreme Suite (SaaS platform)",
    url: "https://supreme-suite.vercel.app",
    description:
      "13-system white-label SaaS — ready-made CRMs + branded sites + AI staff on 3-day trials. Self-checks every route via /api/health; operator panel at /suite.",
    categoryId: "products",
    tags: ["saas", "nextjs", "production", "self-checked"],
    featured: true,
    vercelProjectName: "supreme-suite",
  },
  {
    id: "j-supreme-tech-website",
    name: "J Supreme Tech Website",
    url: "https://jsupremetech.online",
    description: "JST public site — B&W mono revamp with device mockups + project showcase.",
    categoryId: "internal",
    tags: ["jst", "nextjs", "production", "custom-domain"],
    featured: true,
    vercelProjectName: "j-supreme-tech-website",
  },
  {
    id: "jsupremetechportfolio",
    name: "J Supreme Tech Portfolio",
    url: "https://jsupreme-behance-handoff.vercel.app",
    description: "Behance-style portfolio handoff site.",
    categoryId: "internal",
    tags: ["portfolio", "static"],
    vercelProjectName: "jsupremetechportfolio",
  },
  {
    id: "j-supreme-marketing-web",
    name: "J Supreme Marketing Web",
    url: "https://j-supreme-marketing-web.vercel.app",
    description: "J Supreme Marketing arm — Spotlight B&W rebrand.",
    categoryId: "internal",
    tags: ["marketing", "nextjs"],
    vercelProjectName: "j-supreme-marketing-web",
  },
  {
    id: "jsuprememarketinsititue",
    name: "J Supreme Market Institute",
    url: "https://jsuprememarketinsititue-jordan-sketch-hues-projects.vercel.app",
    description: "Trading institute / market-education workspace. ⚠ Latest deploy errored.",
    categoryId: "internal",
    tags: ["trading", "education"],
    vercelProjectName: "jsuprememarketinsititue",
  },

  // ----------------------------------------------------------------- Clients
  {
    id: "courier-app",
    name: "BP Couriers (Courier App)",
    url: "https://bpcouriers.online",
    description: "BP Couriers ops/booking app (Clerk + Supabase + Payload).",
    categoryId: "clients",
    tags: ["logistics", "nextjs", "app", "custom-domain"],
    vercelProjectName: "courier-app",
  },
  {
    id: "aboo-tours",
    name: "Aboo Tours",
    url: "https://www.abootours.com",
    description: "Jamaican tourism + airport-transfer booking platform.",
    categoryId: "clients",
    tags: ["travel", "booking", "vite"],
    vercelProjectName: "aboo-tours",
  },
  {
    id: "the-mover-guy",
    name: "The MoverGuy",
    url: "https://themoverguy.online",
    description: "Moving & storage platform — quotes, storage e-sign agreements, back office.",
    categoryId: "clients",
    tags: ["moving", "nextjs", "supabase"],
    vercelProjectName: "the-mover-guy",
  },
  {
    id: "thelanguagecradle",
    name: "The Language Cradle",
    url: "https://thelanguagecradle.com",
    description: "IBLC flagship language site + CMS back-office (password-gated /admin).",
    categoryId: "clients",
    tags: ["education", "nextjs", "supabase", "custom-domain"],
    vercelProjectName: "thelanguagecradle",
  },
  {
    id: "language-cradle-app",
    name: "Language Cradle — Portal",
    url: "https://language-cradle-app.vercel.app",
    description: "Role-portal app (Clerk allowlist + Supabase) for IBLC.",
    categoryId: "clients",
    tags: ["education", "nextjs", "portal"],
    vercelProjectName: "language-cradle-app",
  },
  {
    id: "solidtrust-courier",
    name: "Solid Trust Courier",
    url: "https://solidtrustservices.com",
    description: "Freight-forwarding platform — live Supabase backend, staff invites, payments toggle.",
    categoryId: "clients",
    tags: ["logistics", "nextjs", "supabase", "custom-domain"],
    vercelProjectName: "solidtrust-courier",
  },
  {
    id: "the-cleanser-ja",
    name: "The Cleanser JA",
    url: "https://thecleanserja.com",
    description: "Herbal wellness e-commerce + admin. Also hosts your verified Resend domain.",
    categoryId: "clients",
    tags: ["ecommerce", "nextjs", "custom-domain"],
    vercelProjectName: "the-cleanser-ja",
  },
  {
    id: "solace-auto-imports",
    name: "Solace Auto Imports",
    url: "https://solaceautoimportsltd.com",
    description: "Vehicle-import inventory gallery (Tailwind/JSON-driven).",
    categoryId: "clients",
    tags: ["auto", "static", "custom-domain"],
    vercelProjectName: "solace-auto-imports",
  },
  {
    id: "damazin-by-dee",
    name: "D'Amazin by Dee",
    url: "https://damazin-by-dee.vercel.app",
    description: "Clinical / medical supplies brand site.",
    categoryId: "clients",
    tags: ["medical", "vite"],
    vercelProjectName: "damazin-by-dee",
  },
  {
    id: "nexpro",
    name: "NEXPRO",
    url: "https://nexpro-sigma.vercel.app",
    description: "Agri-tech food-security platform + NEXLINK surplus-food alerts.",
    categoryId: "clients",
    tags: ["agritech", "nextjs"],
    vercelProjectName: "nexpro",
  },
  {
    id: "trella-marketing",
    name: "Trella Marketing",
    url: "https://trella-marketing.vercel.app",
    description: "Marketing-consultancy platform (site + /portal + /admin CRM).",
    categoryId: "clients",
    tags: ["marketing", "nextjs"],
    vercelProjectName: "trella-marketing",
  },
  {
    id: "trella-marketing-app",
    name: "Trella — App",
    url: "https://trella-marketing-app.vercel.app",
    description: "Trella dual-role companion app (static export).",
    categoryId: "clients",
    tags: ["marketing", "app"],
    vercelProjectName: "trella-marketing-app",
  },
  {
    id: "only-source-wholesale",
    name: "Only Source Wholesale",
    url: "https://only-source-wholesale.vercel.app",
    description: "Wholesale catalog and business web presence.",
    categoryId: "clients",
    tags: ["wholesale", "vite"],
    vercelProjectName: "only-source-wholesale",
  },
  {
    id: "island-rise-events",
    name: "Island Rise Events",
    url: "https://island-rise-events.vercel.app",
    description: "Events site and campaign experience.",
    categoryId: "clients",
    tags: ["events", "vite"],
    vercelProjectName: "island-rise-events",
  },
  {
    id: "infinitteherbs",
    name: "Infinitte Herbs",
    url: "https://infinitteherbs.vercel.app",
    description: "Wellness / herbal product brand site.",
    categoryId: "clients",
    tags: ["wellness", "static"],
    vercelProjectName: "infinitteherbs",
  },
  {
    id: "lingua-caribe",
    name: "Lingua Caribe",
    url: "https://lingua-caribe.vercel.app",
    description: "Caribbean language & culture web property.",
    categoryId: "clients",
    tags: ["language", "static"],
    vercelProjectName: "lingua-caribe",
  },
  {
    id: "islandbridge-freight",
    name: "Islandbridge Freight",
    url: "https://islandbridge-freight.vercel.app",
    description: "Freight, logistics, and service website.",
    categoryId: "clients",
    tags: ["freight", "vite"],
    vercelProjectName: "islandbridge-freight",
  },
  {
    id: "islandrelay",
    name: "IslandRelay",
    url: "https://empty-window-eight.vercel.app",
    description: "Island service workflow project.",
    categoryId: "clients",
    tags: ["service", "nextjs"],
    vercelProjectName: "islandrelay",
  },
  {
    id: "carib-ortho-supply",
    name: "Carib Ortho Supply",
    url: "https://carib-ortho-supply.vercel.app",
    description: "Medical / orthopedic supply web platform.",
    categoryId: "clients",
    tags: ["medical", "vite"],
    vercelProjectName: "carib-ortho-supply",
  },
  {
    id: "supplyandemand",
    name: "Supply and Demand",
    url: "https://supplyandemand.vercel.app",
    description: "Supply & demand service marketplace.",
    categoryId: "clients",
    tags: ["marketplace", "static"],
    vercelProjectName: "supplyandemand",
  },
  {
    id: "sortedja",
    name: "Sorted JA",
    url: "https://sortedja.vercel.app",
    description: "Jamaica-focused service and directory platform.",
    categoryId: "clients",
    tags: ["directory", "vite"],
    vercelProjectName: "sortedja",
  },
  {
    id: "fora-web",
    name: "Fora Web",
    url: "https://fora-web.vercel.app",
    description: "Client web launch.",
    categoryId: "clients",
    tags: ["client", "nextjs"],
    vercelProjectName: "fora-web",
  },
  {
    id: "wander",
    name: "Wander",
    url: "https://wander-henna.vercel.app",
    description: "Travel & lifestyle web experience.",
    categoryId: "clients",
    tags: ["travel", "static"],
    vercelProjectName: "wander",
  },

  // ------------------------------------------------------ Product & ventures
  {
    id: "courier-logistics",
    name: "Stratus Courier (Logistics)",
    url: "https://courier-logistics.vercel.app",
    description: "Full courier logistics platform — 4 portals + marketing. Mock data.",
    categoryId: "products",
    tags: ["logistics", "nextjs", "demo"],
    vercelProjectName: "courier-logistics",
  },
  {
    id: "crown-district-ja",
    name: "Crown District JA",
    url: "https://crown-district-ja.vercel.app",
    description: "Streetwear e-commerce ecosystem (shop + account + admin). Mock data.",
    categoryId: "products",
    tags: ["ecommerce", "nextjs", "demo"],
    vercelProjectName: "crown-district-ja",
  },
  {
    id: "fabworks-ja",
    name: "ForgeWorks (Fabworks)",
    url: "https://fabworks-ja.vercel.app",
    description: "Fabrication ecosystem rebuild — marketing + portal + worker + admin.",
    categoryId: "products",
    tags: ["fabrication", "nextjs", "demo"],
    vercelProjectName: "fabworks-ja",
  },
  {
    id: "forgeworks-jamaica",
    name: "ForgeWorks (original)",
    url: "https://forgeworks-jamaica.vercel.app",
    description: "Original ForgeWorks fabrication demo (auto-restoring scaffold — don't edit).",
    categoryId: "products",
    tags: ["fabrication", "nextjs", "demo"],
    vercelProjectName: "forgeworks-jamaica",
  },
  {
    id: "ridelink-jamaica",
    name: "RideLink Jamaica",
    url: "https://ridelink-jamaica.vercel.app",
    description: "Ride-hailing + courier super app (rider/driver/admin). Mock data.",
    categoryId: "products",
    tags: ["mobility", "nextjs", "demo"],
    vercelProjectName: "ridelink-jamaica",
  },
  {
    id: "lumina-entertainment",
    name: "LUMINA Entertainment",
    url: "https://lumina-entertainment.vercel.app",
    description: "Entertainment-group platform + 12-page admin (dark premium).",
    categoryId: "products",
    tags: ["entertainment", "nextjs", "demo"],
    vercelProjectName: "lumina-entertainment",
  },
  {
    id: "lumina-entertainment-light",
    name: "LUMINA — Light",
    url: "https://lumina-entertainment-light.vercel.app",
    description: "White-dominant copy of LUMINA Entertainment.",
    categoryId: "products",
    tags: ["entertainment", "nextjs", "demo"],
    vercelProjectName: "lumina-entertainment-light",
  },
  {
    id: "tend-life-coo",
    name: "Tend (Life COO)",
    url: "https://tend-life-coo.vercel.app",
    description: "Life-COO agency venture site (marketing + portal + admin).",
    categoryId: "products",
    tags: ["venture", "nextjs", "demo"],
    vercelProjectName: "tend-life-coo",
  },
  {
    id: "conduit-automation",
    name: "Conduit (Automation)",
    url: "https://conduit-automation.vercel.app",
    description: "AI automation-studio venture site.",
    categoryId: "products",
    tags: ["venture", "nextjs", "demo"],
    vercelProjectName: "conduit-automation",
  },
  {
    id: "cadence-content-kits",
    name: "Cadence (Content Kits)",
    url: "https://cadence-content-kits.vercel.app",
    description: "DFY content-kit store venture site.",
    categoryId: "products",
    tags: ["venture", "nextjs", "demo"],
    vercelProjectName: "cadence-content-kits",
  },
  {
    id: "testloop",
    name: "TestLoop",
    url: "https://testloop.online",
    description: "Dev + tester community brand (builders testing builders).",
    categoryId: "products",
    tags: ["community", "nextjs", "custom-domain"],
    vercelProjectName: "testloop",
  },

  // ------------------------------------------------------------- Experiments
  {
    id: "aboo-promo",
    name: "Aboo Tours — Promo",
    url: "https://aboo-promo.vercel.app",
    description: "Aboo Tours promo microsite.",
    categoryId: "experiments",
    tags: ["promo", "static"],
    vercelProjectName: "aboo-promo",
  },
  // Note: the empty `jader` scratch project (no deployment, no domain) is
  // intentionally omitted. It will appear under "On Vercel (auto)" only if you
  // connect the Vercel token and it ever gets a deployment.
];
